# Generated by Django 5.1 on 2025-05-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspiRy', '0002_post_post_image_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='InspiRy.user'),
            preserve_default=False,
        ),
    ]
